# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    permissions:
     actions: read
     contents: write
     
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        cache: true
        cache-dependency-path: go-feather-action/go.sum 

    - name: Build
      working-directory: go-feather-action
      run: |
        go build -v -o feather-binary ./cmd/fledge

    - name: Upload Binary Artifact
      uses: actions/upload-artifact@v4
      with:
        name: feather-binary
        path: go-feather-action/feather-binary
